<?php

/**
 * @file
 * Test API
 */

function rest_router_test_rest_endpoints() {
  return array(
    'rest_router_test' => array(
      'path' => '_rest_router_test',
      'name' => 'Rest Router Test',
      'versions' => array(
        '1.0' => array(
          'router' => 'RestRouterTestRouterV1',
          'class'  => 'RestRouterTestApiV1',
        ),
        '2.0' => array(
          'router' => 'RestRouterTestRouterV2',
          'class'  => 'RestRouterTestApiV2',
        ),
      ),
      'default version' => '1.0',
      'auth' => array(
        'oauth' => array('type' => '2legged', 'context' => 'rest_router_test'),
      ),
      'version' => array('path' => array()),
    ),
    'rest_router_test_basic' => array(
      'path' => '_rest_router_test_basic',
      'name' => 'Rest Router Test BasicAuth',
      'versions' => array(
        '1.0' => array(
          'router' => 'RestRouterTestBasicAuthRouter',
          'class'  => 'RestRouterTestBasicAuthApi',
        ),
      ),
      'default version' => '1.0',
      'auth' => array(
        'basic' => array(),
      ),
      'version' => array('path' => array()),
    ),
  );
}
